# Generated by Django 4.2.15 on 2025-06-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_email_verified",
        ),
    ]
