# Generated by Django 4.2.15 on 2025-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0048_alter_serviceimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="is_featured",
            new_name="top_event",
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("employment", "Employment"),
                    ("food", "Food & Dining"),
                    ("business", "Business"),
                    ("festival", "Festival"),
                    ("art", "Art & Culture"),
                    ("sport", "Sport"),
                    ("music", "Music"),
                    ("education", "Education"),
                    ("technology", "Technology"),
                    ("health", "Health & Wellness"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
