# Generated by Django 4.2.15 on 2025-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0049_rename_is_featured_event_top_event_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("product", "Product Business"),
                    ("service", "Service Business"),
                    ("both", "Product & Service Business"),
                ],
                max_length=20,
            ),
        ),
    ]
