# Generated by Django 4.2.15 on 2025-06-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0051_alter_business_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                default="business/assets/images/banner/1.png",
                null=True,
                upload_to="business_banners/",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="business/assets/images/banner/1.png",
                null=True,
                upload_to="business_profiles/",
            ),
        ),
    ]
