# Generated by Django 4.2.15 on 2025-06-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0052_alter_business_banner_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                default="business_profiles/DukaniEthnicStore.png",
                null=True,
                upload_to="business_banners/",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="business_profiles/DukaniEthnicStore.png",
                null=True,
                upload_to="business_profiles/",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/additional_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="business.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
