# Generated by Django 4.2.15 on 2025-06-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0053_alter_business_banner_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="max_delivery_time",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_delivery_time",
        ),
    ]
