# Generated by Django 4.2.15 on 2025-06-29 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0054_remove_product_max_delivery_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                default="pickup",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tip_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="DeliveryQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_id", models.CharField(max_length=100, unique=True)),
                ("pickup_address", models.TextField()),
                ("dropoff_address", models.TextField()),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                ("pickup_time_estimated", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time_estimated", models.DateTimeField(blank=True, null=True)),
                ("quote_data", models.JSONField()),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_delivery_id", models.CharField(max_length=100)),
                (
                    "doordash_delivery_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("created", "Created"),
                            ("dasher_confirmed", "Dasher Confirmed"),
                            ("picked_up", "Picked Up"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("tracking_url", models.URLField(blank=True, null=True)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tip_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("pickup_address", models.TextField()),
                ("dropoff_address", models.TextField()),
                ("pickup_time_estimated", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time_estimated", models.DateTimeField(blank=True, null=True)),
                ("pickup_time_actual", models.DateTimeField(blank=True, null=True)),
                ("dropoff_time_actual", models.DateTimeField(blank=True, null=True)),
                ("delivery_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.deliveryquote",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="business.order",
                    ),
                ),
            ],
        ),
    ]
