# Generated by Django 4.2.15 on 2025-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0055_order_delivery_fee_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="postcode",
            field=models.CharField(
                default="5000", help_text="4-digit Australian postcode", max_length=4
            ),
        ),
    ]
