"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'users.CustomUser'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9%kas3mq31%5q6)o#gm_ka%6e465_x_3(d0@6dn%@f_4k)vu5y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',  # Change this to 'INFO' to avoid debug messages
        },
    },
}


# DoorDash Drive API Configuration
DOORDASH_DEVELOPER_ID = '811c829f-1159-4a96-b927-112a6ccc5e8e'  # From your screenshot
DOORDASH_KEY_ID = 'a76ac2a7-09df-4635-a5cb-86f3edbf3a06'  # From your screenshot
DOORDASH_SIGNING_SECRET = 'OoAaVZ-ij_r4c0kM0kJTg7qOB7fP8MzPq7jyhZ6oIU'  # From your screenshot
DOORDASH_BASE_URL = 'https://openapi.doordash.com/drive/v2'  # Sandbox URL

# Google Maps API Configuration
GOOGLE_MAPS_API_KEY = 'AIzaSyD_jODWQ-KDeU65Sr4xOALQsZ7mwI3q7h4'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'business.apps.BusinessConfig',
    'users.apps.UsersConfig',
    'bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'business.middleware.NoDebugMessagesMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'business.middleware.AjaxMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'business.context_processors.cart_data',
                'business.context_processors.cart_item_count',
                'business.context_processors.unread_message_count',
                'business.context_processors.business_order_count',
                'business.context_processors.popular_products',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "dukaniethnicstore@gmail.com"
EMAIL_HOST_PASSWORD = "cquh pjqh hlyi cafy"
DEFAULT_FROM_EMAIL = "dukaniethnicstore@gmail.com"


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Adelaide'

USE_I18N = True

USE_TZ = True




# Stripe settings
#STRIPE_SECRET_KEY = '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'
#STRIPE_PUBLIC_KEY = 'pk_live_51PVl0mRvafFWMAqoRdQSQ6c7bjc4ygSkDWh7fMGk9iiT9xQKw0tbaiKy6QTQvllVMc8E471xMA4O4qhTQXuNmi3X00siAayXXj'


STRIPE_SECRET_KEY = 'sk_test_51P4gElP9SsicgG1jiHrOYu86MB4PNBRKMTxSgCHrCpPGaWrs68tkgtsUMx8CBZ7Nv0BXd9nFMAyuia4mSEo60Tdj00iH6Li1dk'
STRIPE_PUBLIC_KEY = 'pk_test_51P4gElP9SsicgG1jB3b9vewTDC2pbRh3YOUKAaavO88BIFyqQgIg3FJzmy9NDwitrtwS8BXHUYhG2R2WtuuqfLFw00ZdmOuvHt'
STRIPE_PRODUCT_BUSINESS_PRICE_ID = 'price_1RHUo2P9SsicgG1jYieDVTOO'  # A$12/month with 3-month free trial
STRIPE_SERVICE_BUSINESS_PRICE_ID = 'price_1RHUovP9SsicgG1jY0FLVRg1'  # A$10/month with 3-month free trial
STRIPE_BOTH_BUSINESS_PRICE_ID = 'price_1RHUpcP9SsicgG1jFQtfzR1C'     # A$20/month with 3-month free trial


SHIPPIT_API_KEY = '9DKhF5UavAlLZioVVJxUsA'  # Your Shippit API key
SHIPPIT_API_URL = 'https://app.shippit.com/api/3'  # Shippit API endpoint
SHIPPIT_ENVIRONMENT = 'sandbox'  # or 'production' for production


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = ''

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRs = [
    os.path.join(BASE_DIR, 'static'),
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
