"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'users.CustomUser'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9%kas3mq31%5q6)o#gm_ka%6e465_x_3(d0@6dn%@f_4k)vu5y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Create logs directory if it doesn't exist
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Formatters define how log messages are formatted
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%H:%M:%S'
        },
        'detailed': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },

    # Handlers define where logs go
    'handlers': {
        # Console handler (what you see in terminal)
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # File handler for all logs
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',  # Rotates automatically
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,  # Keep 5 backup files
            'formatter': 'detailed',
        },
        # Separate file for EasyShip logs
        'easyship_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'easyship.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'detailed',
        },
        # Error logs only
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'errors.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },

    # Loggers define which handlers receive logs
    'loggers': {
        # Django's built-in logger
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        # Your business app logger
        'business': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # EasyShip service logger
        'business.easyship_service': {
            'handlers': ['console', 'easyship_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Your other loggers
        'users': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },

    # Root logger catches everything else
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
}

# DoorDash Drive API Configuration
DOORDASH_DEVELOPER_ID = '811c829f-1159-4a96-b927-112a6ccc5e8e'  # From your screenshot
DOORDASH_KEY_ID = 'a76ac2a7-09df-4635-a5cb-86f3edbf3a06'  # From your screenshot
DOORDASH_SIGNING_SECRET = 'OoAaVZ-ij_r4c0kM0kJTg7qOB7fP8MzPq7jyhZ6oIU'  # From your screenshot
DOORDASH_BASE_URL = 'https://openapi.doordash.com/drive/v2'  # Sandbox URL



# Keep session alive for 2 hours — long enough to complete registration + Stripe onboarding
SESSION_COOKIE_AGE = 7200
SESSION_SAVE_EVERY_REQUEST = True


# Google Maps API Configuration
#GOOGLE_MAPS_API_KEY = 'AIzaSyB0VtUqG6fKAi75im1nyZFHFHPfBmzH3j8'
GOOGLE_MAPS_API_KEY = 'AIzaSyA1Fn93oOxNsLhhc3DjYhcaPik8AlC2rEA'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'business.apps.BusinessConfig',
    'users.apps.UsersConfig',
    'bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'business.middleware.NoDebugMessagesMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'business.middleware.AjaxMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameAuthBackend',  # Custom backend (FIRST!)
    'django.contrib.auth.backends.ModelBackend',   # Default backend (fallback)
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'business.context_processors.cart_data',
                'business.context_processors.cart_item_count',
                'business.context_processors.unread_message_count',
                'business.context_processors.business_order_count',
                'business.context_processors.popular_products',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "dukaniethnicstore@gmail.com"
EMAIL_HOST_PASSWORD = "cquh pjqh hlyi cafy"
DEFAULT_FROM_EMAIL = "dukaniethnicstore@gmail.com"


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Adelaide'

USE_I18N = True

USE_TZ = True


# Stripe settings
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY')


#STRIPE_SECRET_KEY = 'sk_test_51P4gElP9SsicgG1jiHrOYu86MB4PNBRKMTxSgCHrCpPGaWrs68tkgtsUMx8CBZ7Nv0BXd9nFMAyuia4mSEo60Tdj00iH6Li1dk'
#STRIPE_PUBLIC_KEY = 'pk_test_51P4gElP9SsicgG1jB3b9vewTDC2pbRh3YOUKAaavO88BIFyqQgIg3FJzmy9NDwitrtwS8BXHUYhG2R2WtuuqfLFw00ZdmOuvHt'

#test
#STRIPE_PRODUCT_BUSINESS_PRICE_ID = 'price_1RHUo2P9SsicgG1jYieDVTOO'  # A$12/month with 3-month free trial
#STRIPE_SERVICE_BUSINESS_PRICE_ID = 'price_1RHUovP9SsicgG1jY0FLVRg1'  # A$10/month with 3-month free trial
#STRIPE_BOTH_BUSINESS_PRICE_ID = 'price_1RHUpcP9SsicgG1jFQtfzR1C'     # A$20/month with 3-month free trial

STRIPE_PRODUCT_BUSINESS_PRICE_ID = 'price_1THR9MRvafFWMAqotYkJHxF0'  # A$12/month with 3-month free trial
STRIPE_SERVICE_BUSINESS_PRICE_ID = 'price_1THRApRvafFWMAqouB3NTod6'  # A$10/month with 3-month free trial
STRIPE_BOTH_BUSINESS_PRICE_ID = 'price_1THRASRvafFWMAqoTbY8lKtU'     # A$20/month with 3-month free trial
#STRIPE_BOTH_BUSINESS_PRICE_ID = 'price_1TT1K0RvafFWMAqouqplVnN8'

# ShipStation Configuration
SHIPSTATION_API_KEY = 'acDM36M+MgpnpJEk20gjA+F5gQCTYu1ZCYdNydXCtpE'
SHIPSTATION_API_SECRET = ''  # You might need this from your account
SHIPSTATION_BASE_URL = 'https://api.shipstation.com'  # Production
SHIPSTATION_SANDBOX_URL = 'https://docs.shipstation.com/_mock/openapi'  # Sandbox
SHIPSTATION_USE_SANDBOX = False  # Set to False for production


EASYSHIP_SANDBOX_TOKEN    = 'sand_lClOJZEjEMzctPittAKsxqyQ4+TbUp48potfeLCUEAY='
EASYSHIP_PRODUCTION_TOKEN = 'prod_KDVcSHO95GxLAj20/pTfsSN/T1q4SsiSR9yAyp6Su08=+FE='
EASYSHIP_USE_SANDBOX      = False   # ← flip to False when ready to go live


#EASYSHIP_SANDBOX_TOKEN    = 'sand_ryjnmvKRVNtISLSK+KuDOK2Ag2oiXhl1zCLF/qzr4IY='
#EASYSHIP_PRODUCTION_TOKEN = 'prod_XEwn4rsGUn9ry1jdrFEmmu9BW98mOzdyICH8WU37+FE='
#EASYSHIP_USE_SANDBOX      = True   # ← flip to False when ready to go live

# The public URL EasyShip will POST webhook events to.
# Must be reachable from the internet (not localhost).
EASYSHIP_WEBHOOK_URL = 'https://www.dukaniethnicstore.com.au/webhooks/easyship/'

#Sendle
SENDLE_API_KEY = 'sandbox_nhY3NZP8QKBsbmYry5VZKqPS'  # Your Sendle API Key
SENDLE_SENDER_ID = 'SANDBOX_abrarshahriar360_yah'    # Your Sendle Sender ID

# Sendle Environment
# Set to False for production, True for testing
SENDLE_USE_SANDBOX = True


# Default shipping settings
DEFAULT_PACKAGE_WEIGHT_KG = 1.0  # Default weight if not specified
DEFAULT_PACKAGE_VOLUME_M3 = 0.001  # Default volume if not specified

# Shipping buffer days (how many days ahead to schedule pickup)
SHIPPING_PICKUP_BUFFER_DAYS = 1

SHIPPIT_API_KEY = 'ir5RenGkfkNS-N6rAIabhA'  # Your Shippit API key
SHIPPIT_API_URL = 'https://app.shippit.com/api/3'  # Shippit API endpoint
SHIPPIT_ENVIRONMENT = 'sandbox'  # or 'production' for production


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = ''

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRs = [
    os.path.join(BASE_DIR, 'static'),
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
